### ISSUE TITLE
Crash when use scrollToPosition 

### ISSUE THREAD

**Issue by studentapptdt** [bgogetap/StickyHeaders#18]
(Sorry for my English skill @@)
Yes as title, i get crash when use scrollToPosition
Have any solution for fix it? Thank you so much.
Here my log
`ava.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.support.v7.widget.RecyclerView$LayoutParams
                                                                        at android.support.v7.widget.RecyclerView.getChildViewHolderInt(RecyclerView.java:3979)
                                                                        at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:7719)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3388)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3135)
                                                                        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                                        at android.view.View.layout(View.java:17938)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                        at android.view.View.layout(View.java:17938)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                        at android.view.View.layout(View.java:17938)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                        at android.view.View.layout(View.java:17938)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                        at android.view.View.layout(View.java:17938)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
                                                                        at android.view.View.layout(View.java:17938)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                        at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                        at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1364)
                                                                        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:852)
                                                                        at android.view.View.layout(View.java:17938)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                        at android.view.View.layout(View.java:17938)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                        at android.view.View.layout(View.java:17938)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                        at android.view.View.layout(View.java:17938)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                        at android.view.View.layout(View.java:17938)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                        at android.view.View.layout(View.java:17938)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3193)
                                                                        at android.view.View.layout(View.java:17938)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2666)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)`

**Comment by bgogetap** [comment]
I was able to reproduce this, thanks. I will look into it today or tomorrow.

**Comment by studentapptdt** [comment]
wait for update from you. Thank

**Comment by bgogetap** [comment]
@studentapptdt Please try the latest version (0.3.2). The crash for this issue should be fixed but I very rarely noticed the header not getting bound if using scrollToPosition (though smoothScrollToPosition works fine).

Open another issue if you find any problems with the latest release.
