### ISSUE TITLE
Nullpointer Exception in StickyLayoutManager

### ISSUE THREAD

**Issue by MinkiPan** [bgogetap/StickyHeaders#46]
> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.brandongogetap.stickyheaders.c.a(java.util.List)' on a null object reference
at com.brandongogetap.stickyheaders.StickyLayoutManager.cacheHeaderPositions(SourceFile:97)
at com.brandongogetap.stickyheaders.StickyLayoutManager.onLayoutChildren(SourceFile:78)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(SourceFile:3583)
at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile:3312)
at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(SourceFile:1618)
at android.support.v7.widget.RecyclerView$ViewFlinger.run(SourceFile:4702)
at android.os.Handler.handleCallback(Handler.java:743)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5665)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)

okay seems like the `positioner` in `StickyLayoutManager ` is null while attempting to call it
I saw positioner is instantiated in onAttachWindows, and seems like layoutChildren is called before onAttachToWindows which causes afterwards the crash

its our second most occurring bug in our production, please fix it 
thanks

**Comment by bgogetap** [comment]
Please feel free to fork and fix it for your project if it is that urgent.

I will try to reproduce when I have a chance.

**Comment by bgogetap** [comment]
I wish I could reproduce this, but for now I did what I didn't want to do and went with some null checks.

I do still cache the header positions, and once `onAttachedToWindow` is called, I re-init the positioner so hopefully, in the cases where layout happens before attach, sticky headers still work as expected.

**Comment by MinkiPan** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewTreeObserver android.view.View.getViewTreeObserver()' on a null object reference
                                                                      at com.brandongogetap.stickyheaders.StickyHeaderPositioner$3.onGlobalLayout(StickyHeaderPositioner.java:289)
                                                                      at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2107)
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

the fix introduced unfortunately a new bug
can you fix that?

**Comment by bgogetap** [comment]
Uploaded 0.4.7

0.4.6 was live for a very short period (a couple minutes), but I deleted it from jcenter so don't try to import that one.
