### ISSUE TITLE
It is possible use SwipeRefreshLayout as parent view 

### ISSUE THREAD

**Issue by davidHarush** [bgogetap/StickyHeaders#78]
it is possible use SwipeRefreshLayout as parent view in addition to FrameLayout or use SwipeRefreshLayout?

> Make sure the parent of the RecyclerView is a FrameLayout or CoordinatorLayout (this will be verified at Runtime)

Thanks...

**Comment by bgogetap** [comment]
SwipeRefreshLayout only supports one child, so this library could not work with it since the header is added as a child view of the RecyclerView's parent.

SwipeRefreshLayout still works just fine with the FrameLayout that hosts the RecyclerView put inside it:

SwipeRefreshLayout
-FrameLayout
--RecyclerView

**Comment by davidHarush** [comment]
` java.lang.IllegalArgumentException: RecyclerView parent must be either a FrameLayout or CoordinatorLayout
        at com.brandongogetap.stickyheaders.Preconditions.validateParentView(Preconditions.java:23)
        at com.brandongogetap.stickyheaders.StickyLayoutManager.onAttachedToWindow(StickyLayoutManager.java:123)
        at android.support.v7.widget.RecyclerView$LayoutManager.dispatchAttachedToWindow(RecyclerView.java:7739)
.
.
.`

from --> `static void validateParentView(View recyclerView)`

**Comment by davidHarush** [comment]
My mistake, seems to be working, Thanks
