### ISSUE TITLE
NPE on StickyHeaderPositioner.getHeaderPositionToShow()

### ISSUE THREAD

**Issue by zecweb** [bgogetap/StickyHeaders#89]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.brandongogetap.stickyheaders.StickyHeaderPositioner.getHeaderPositionToShow(StickyHeaderPositioner.java:192)
       at com.brandongogetap.stickyheaders.StickyHeaderPositioner.updateHeaderState(StickyHeaderPositioner.java:60)
       at com.brandongogetap.stickyheaders.StickyLayoutManager.scrollVerticallyBy(StickyLayoutManager.java:95)
       at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1832)
       at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:1927)
       at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3187)
       at android.view.View.dispatchTouchEvent(View.java:10098)

**Comment by bgogetap** [comment]
Thanks for reporting. Do you have steps to reproduce this?

**Comment by zecweb** [comment]
I can't reproduce it. I'm seeing this from crashlytics.
